name: Run Laravel Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      sqlite:
        image: nouchka/sqlite3

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.2'
          extensions: mbstring, intl, pdo_sqlite
          coverage: none

      - name: Install Composer Dependencies
        run: composer install --no-scripts --no-progress --prefer-dist

      - name: Copy Environment File
        run: cp .env.example .env

      - name: Generate App Key
        run: php artisan key:generate

      - name: Run Migrations (SQLite in-memory)
        run: php artisan migrate --database=sqlite

      - name: Run Tests
        run: php artisan test
